### ISSUE TITLE
一直登陆失败。。

### ISSUE THREAD

**Issue by firefoxer1992** [wangxinforme/springmvc#2]
sql已经导入，输入账号密码一直报错。。
是因为shiro的权限验证原因吗？subject.isAuthenticated()一直都是false。。
UserServiceImpl.java里面的findUserByName()方法一直报错： # 根据账号查询用户报错
日志如下所示：
![default](https://user-images.githubusercontent.com/8308355/33418317-43d88672-d5e0-11e7-8497-bd7d18b0b48a.png)

**Comment by wangxinforme** [comment]
sql建表执行后，还需要执行Junit进行数据初始化操作，再试试看，有问题，可以加我微信，最近项目忙，上github少
